version: "3"
services:
  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=1338
    volumes:
      - ./:/home/node/app
    ports:
        - "1338:1338"
    command: "npm start"
  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=1337
    volumes:
      - ./:/home/node/app
    ports:
        - "1337:1337"
    command: "npm start"
  node6:
    image: "node:6"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=1336
    volumes:
      - ./:/home/node/app
    ports:
        - "1336:1336"
    command: "npm start"
