version: "3"
services:
  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=1338
    volumes:
      - ./:/home/node/app
    ports:
        - "1338:1338"
    command: "npm test"

  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=1337
    volumes:
      - ./:/home/node/app
    ports:
        - "1337:1337"
    command: "npm test"

  node6:
    image: "node:6"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=1336
    volumes:
      - ./:/home/node/app
    ports:
        - "1336:1336"
    command: "npm test"

  server:
    build:
      context: .
      dockerfile: .dockerfiles/node9
    ports:
      - "${DBWEBB_PORT:-3000}:3000"
    command: "npm start"
